version: '3'

services:
  consul-server:
    container_name: consul-server
    image: consul:latest
    ports:
      - '8500:8500'
    command: "agent -server -ui -node=consul-server -bootstrap-expect=1 -client 0.0.0.0 -bind=127.0.0.1"
    volumes:
      - ./config:/consul/config
